#security:
#    firewalls:
#        secured_area:
#            pattern:    ^/
#            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"

security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_USER:       ROLE_USER
        ROLE_ADMIN: ROLE_ADMIN

    providers:
#        in_memory:
#            memory:
#                users:
#                    ryan:  { password: ryanpass, roles: 'ROLE_USER' }
#                    admin: { password: kitten, roles: 'ROLE_ADMIN' }
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
#        secured_area:
#            pattern:    ^/
#            anonymous: ~
#            http_basic:
#                realm: "Secured Demo Area"
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
            logout:       true
            anonymous:    true

    access_control:
        - { path: ^/(ru|en)/admin, role: ROLE_ADMIN }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }