<?php

namespace Main\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BranchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BranchRepository extends EntityRepository
{
    public function getListBranches($chain_url, $city_id, $_locale)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('b')
            ->from('MainBundle:Branch', 'b')
            ->join('b.chain','c')

            ->where('c.url = :chain_url')
            ->andWhere('c.city_id = :city_id')
            ->andWhere('c.lang = :lang')
            ->andWhere('b.lang = :lang')

            ->setParameter('chain_url', $chain_url)
            ->setParameter('city_id',$city_id)
            ->setParameter('lang',$_locale)
            ;

        return $query->getQuery()->getResult();
    }

}
