<?php

    namespace Main\Bundle\Entity;

    use Doctrine\ORM\EntityRepository;

    /**
     * DiscountRepository
     *
     * This class was generated by the Doctrine ORM. Add your own custom
     * repository methods below.
     */
    class DiscountRepository extends EntityRepository
    {

        public function findSameDiscount($data)
        {
            $em = $this->getEntityManager();

            $query = $em->createQueryBuilder()
                ->select('d')
                ->from('MainBundle:Discount','d')
                ->where('d.chain = :chain')
                ->andWhere('d.city_id = :city_id')
                ->andWhere('d.lang = :lang')
                ->andWhere('d.id <> :not_in_id')
                ->andWhere('d.parent IS NULL')
                ->setParameters($data)
                ->setMaxResults(3)
                ;

            return $query->getQuery()->getResult();
        }
    }
