<?php

namespace Main\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends EntityRepository
{

    /**
     * @return array
     */
    public function getAllWithIndex()
    {
        $em = $this->getEntityManager();

        $query = $em->createQuery('
            SELECT
              ingr
            FROM
              Main\Bundle\Entity\Ingredient ingr
            INDEX BY
              ingr.id
        ');

        return $query->getResult();
    }
}
