<?php

namespace Main\Bundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{

    /**
     * @param array $vars
     * @return array
     */
    public function findOthersItems(array $vars)
    {
        $em = $this->getEntityManager();

        $query = $em->createQueryBuilder()
            ->select('it')
            ->from('MainBundle:Item', 'it')

            ->where('it.chain = :chain')
            ->andWhere('it.id <> :id')

            ->setParameter('chain', $vars['chain'])
            ->setParameter('id', $vars['id'])

            ->orderBy('it.id','DESC')

            ->setMaxResults($vars['limit'])
        ;

        return $query->getQuery()->getResult();
    }


}
